# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Borek Data Ventures UG (haftungsbeschränkt)
# Platform wave 1 — KEDA. Scale-to-zero for idle participant agents/apps
# (stackit.md §5 "Scaling with participants"); complements `make sleep/wake`.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sovereign-os
  source:
    repoURL: https://kedacore.github.io/charts
    chart: keda
    targetRevision: 2.15.1
    helm:
      releaseName: keda
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
